name = "QMSimData"
uuid = "62431b32-dd41-4b4a-a812-2a777c7bd32e"
authors = ["Yutaka Masuda <yutaka@uga.edu>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
